### ISSUE TITLE
Zeva - Balances and reassessments

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1259]
The government issues an Assessment and Re-assessment to suppliers which provides their approved credit balance at the end of each compliance period (30th Sept each year). The 'Assessed balance at end of 30th Sept' on the assessment displays this balance.

Currently, this assessed balance is shown in the subsequent year's model year report, near the top of the compliance obligation page, and on the summary page. It is also displayed on the assessment. This is accurate.

However, when a reassessment is issued, the reassessed balance at end of 30th Sept given in the reassessment should replace the assessed balance from the original assessment or any reassessed balance from prior reassessments.

**Task:**

Update the logic for Model Year Report creation to ensure that the most recent government-issued 'balance at end of 30th Sept' is used as the starting balance for display and calculation in the newly created model year report.
Display the most recent government-issued 'balance at end of 30th Sept' on the credit transactions and detailed balance page, following the new design in card 554.

**Context:**

For example, suppose the 'balance at end of 30th Sept' in the Model Year Report for 2021 was 1, but it was reassessed to be 2. In that case, when a supplier creates a Model Year Report for 2022, it should pull in the most recent government-issued value of 2 from the reassessment instead of the original value of 1.

It's important to note that this logic should only be applied when creating a new Model Year Report; modifying a previous year's balance should not automatically update an existing subsequent Model Year Report's starting balance. A reassessment has to be made to account for that change.

**Acceptance Criteria:**

- [x] When creating a Model Year Report, the most recent 'balance at end of 30th Sept' from the previous year should be pulled in for display and calculation.
- [x] The credit transactions and detailed balance page should display the most recent government-issued 'balance at end of 30th Sept' following the new design in card 554.

**Development Checklist:**

- [x] Update the logic for Model Year Report creation to ensure that it pulls the most recent government-issued 'balance at end of 30th Sept' for the starting balance.
- [x] Verify that the starting balance doesn't automatically change for an existing Model Year Report when the 'balance at end of 30th Sept' in the previous year is changed in a reassessment.

**Notes:**
This issue is linked to the credit transaction page re-design in card 554.

**Comment by kcabhar** [comment]
Comments from Jira:

James 23/Dec/22
Note - the assessed/reassessed values also need to pulled into the following years report and assessment.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1259?planning-poker) with Zenhub @emi-hi @vibhiquartech @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1259?planning-poker) with Zenhub @JulianForeman

**Comment by jdon-zev** [comment]
Close card - to be tested as part of reassessments testing.
